### PR TITLE
ci: use dependabot on GH actions

### PR DESCRIPTION
**Pull request by mestery**
Inspired by: https://github.com/ipdk-io/ipdk/pull/146

Co-authored-by: Boris Glimcher <Boris.Glimcher@emc.com>
Signed-off-by: Kyle Mestery <mestery@mestery.com>

### CODE REVIEW

**Comment by mestery** [comment]
This will ensure the Dependabot pushes PRs once a week to update the versions of our GitHub Actions we use.

**Comment by mestery** [comment]
#38 needs to be merged first so this one can pass the CI.

**Comment by osinstom** [comment]
@mestery I've merged #38. I like this idea - we had also been using dependabot at ONF for some projects. It might require some additional configuration of GHA, but let's see.

**Comment by mestery** [comment]
> @mestery I've merged #38. I like this idea - we had also been using dependabot at ONF for some projects. It might require some additional configuration of GHA, but let's see.

There should not be any additional GHA configuration required, I've added this to both IPDK and ipdk-plugin without requiring changes.

I also rebased this and it's good to merge now!

**Pull request merged**
